name: Scheduled Job

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Install Dependencies
        run: pip
      - name: Run main.py
        run: python main.py